/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TGUI;

import java.util.Random;
import tictactoe.Algorithm;
import tictactoe.Tictactoe;

/**
 *
 * @author 一只水饺
 */
public class CompVSComp extends javax.swing.JFrame {

    int c1Win = 0;
    int c2Win = 0;
    int pin = 0;
    int c1fp=0;
    int c2fp=0;

    Algorithm al = new Algorithm();
    Tictactoe tic = new Tictactoe();

    /**
     * Creates new form Choose
     */
    public CompVSComp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel2.setText("请输入预期对局数：");

        jTextField1.setText("50");

        jButton3.setText("对局开始");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("返回");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(59, 59, 59))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(600, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextArea1.setText("");
        int num = Integer.parseInt(jTextField1.getText());
         c1Win = 0;
         c2Win = 0;
         pin = 0;
        c1fp=0;
        c2fp=0;
        for (int i = 0; i < num; i++) {
            tic.initBroad();
            int fp = firstPlace();
            if (fp == 1) {
                c1fp++;
                jTextArea1.setText(jTextArea1.getText() + "第" + (i+1) + "局：三层深度机器先手" + "\r\n");
                while (true) {
                    
                    int pos = tic.com2Place();
                    jTextArea1.setText(jTextArea1.getText() + "轮到三层深度机器玩家回合，电脑的选择是:" + (pos / 3 + 1) + " " + (pos % 3 + 1) + "\r\n");
                    if (al.gameState(tic.getChess()) == al.WIN || al.gameState(tic.getChess()) == al.LOSE || al.gameState(tic.getChess()) == al.DRAW) {
                        break;
                    }
                    pos = tic.com1Place();
                    jTextArea1.setText(jTextArea1.getText() + "轮到二层深度机器玩家回合，电脑的选择是:" + (pos / 3 + 1) + " " + (pos % 3 + 1) + "\r\n");
                    if (al.gameState(tic.getChess()) == al.WIN || al.gameState(tic.getChess()) == al.LOSE || al.gameState(tic.getChess()) == al.DRAW) {
                        break;
                    }
                }
                
                if(al.gameState(tic.getChess())==al.WIN) {
				jTextArea1.setText(jTextArea1.getText() +"获胜者是三层深度的电脑玩家"+ "\r\n");
				jTextArea1.setText(jTextArea1.getText() +"-------------------------"+ "\r\n");
				c1Win++;
			}else if(al.gameState(tic.getChess())==al.LOSE) {
				jTextArea1.setText(jTextArea1.getText() +"获胜者是二层深度的电脑玩家"+ "\r\n");
				jTextArea1.setText(jTextArea1.getText() +"-------------------------"+ "\r\n");
				c2Win++;
			}else {
				jTextArea1.setText(jTextArea1.getText() +"两位玩家打平"+ "\r\n");
				jTextArea1.setText(jTextArea1.getText() +"-------------------------"+ "\r\n");
				pin++;
			}
            }
            
            else if(fp == 2){
                c2fp++;
                jTextArea1.setText(jTextArea1.getText() + "第" + (i+1) + "局：二层深度机器先手" + "\r\n");
                 while (true) {
                    
                    int pos = tic.com1Place();
                    jTextArea1.setText(jTextArea1.getText() + "轮到二层深度机器玩家回合，电脑的选择是:" + (pos / 3 + 1) + " " + (pos % 3 + 1) + "\r\n");
                    if (al.gameState(tic.getChess()) == al.WIN || al.gameState(tic.getChess()) == al.LOSE || al.gameState(tic.getChess()) == al.DRAW) {
                        break;
                    }
                    pos = tic.com2Place();
                    jTextArea1.setText(jTextArea1.getText() + "轮到三层深度机器玩家回合，电脑的选择是:" + (pos / 3 + 1) + " " + (pos % 3 + 1) + "\r\n");
                    if (al.gameState(tic.getChess()) == al.WIN || al.gameState(tic.getChess()) == al.LOSE || al.gameState(tic.getChess()) == al.DRAW) {
                        break;
                    }
                }
                
                if(al.gameState(tic.getChess())==al.WIN) {
				jTextArea1.setText(jTextArea1.getText() +"获胜者是三层深度的电脑玩家"+ "\r\n");
				jTextArea1.setText(jTextArea1.getText() +"-------------------------"+ "\r\n");
				c1Win++;
			}else if(al.gameState(tic.getChess())==al.LOSE) {
				jTextArea1.setText(jTextArea1.getText() +"获胜者是二层深度的电脑玩家"+ "\r\n");
				jTextArea1.setText(jTextArea1.getText() +"-------------------------"+ "\r\n");
				c2Win++;
			}else {
				jTextArea1.setText(jTextArea1.getText() +"两位玩家打平"+ "\r\n");
				jTextArea1.setText(jTextArea1.getText() +"-------------------------"+ "\r\n");
				pin++;
			}
            }
        }
        
        
        jTextArea2.setText(jTextArea2.getText() +"游戏结果："+ "\r\n");
        jTextArea2.setText(jTextArea2.getText() +"三层深度的电脑玩家先手次数为："+ c1fp+"\r\n");
        jTextArea2.setText(jTextArea2.getText() +"二层深度的电脑玩家先手次数为："+ c2fp+"\r\n");
        jTextArea2.setText(jTextArea2.getText() +"三层深度的电脑玩家获胜次数为："+ c1Win+"\r\n");
        jTextArea2.setText(jTextArea2.getText() +"二层深度的电脑玩家获胜次数为："+ c2Win+"\r\n");
        jTextArea2.setText(jTextArea2.getText() +"两个机器打平的次数为："+ pin+ "\r\n");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new Choose().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public int firstPlace() {

        int num = (int) (1 + Math.random() * (2 - 1 + 1));

        return num;
    }

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompVSComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompVSComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompVSComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompVSComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompVSComp().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
