/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TGUI;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import tictactoe.Algorithm;
import tictactoe.Tictactoe;

/**
 *
 * @author 一只水饺
 */
public class HumanVSComp extends javax.swing.JFrame {
    
    int difficult;
    String name;
    boolean firstplace;
    Tictactoe t3 = new Tictactoe();
    Algorithm al = new Algorithm();
    javax.swing.JButton jButton;
    public HumanVSComp(String name,int difficult,boolean firstplace){
        initComponents();
        this.difficult = difficult;
        this.name = name;
        this.firstplace = firstplace;
        jTextField1.setText(name+",enjoy yourself! ");
        //判断是否是电脑先手
        if(firstplace==false){
           getCompSpet();
           
        }     
        
    }

    /**
     * Creates new form Choose
     */
    public HumanVSComp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        jTextField1.setFont(new java.awt.Font("宋体", 0, 20)); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(3, 3, 1, 1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel2.add(jButton6);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel2.add(jButton7);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel2.add(jButton8);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel2.add(jButton9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(600, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        t3.humanPlace(4);
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
        jButton5.setEnabled(false);
        canContinue();
        getCompSpet();
        canContinue();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        t3.humanPlace(1);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
        jButton2.setEnabled(false);
        canContinue();
        getCompSpet();
        canContinue();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        t3.humanPlace(2);
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
        jButton3.setEnabled(false);
        canContinue();
        getCompSpet();
        canContinue();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        t3.humanPlace(3);
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
        jButton4.setEnabled(false);
        canContinue();
        getCompSpet();
        canContinue();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        t3.humanPlace(5);
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
        jButton6.setEnabled(false);
        canContinue();
        getCompSpet();
        canContinue();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        t3.humanPlace(6);
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
        jButton7.setEnabled(false);
        canContinue();
        getCompSpet();
        canContinue();
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        t3.humanPlace(7);
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
        jButton8.setEnabled(false);
        canContinue();
        getCompSpet();
        canContinue();
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        t3.humanPlace(8);
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
        jButton9.setEnabled(false);
        canContinue();
        getCompSpet();
        canContinue();
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        t3.humanPlace(0);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
        jButton1.setEnabled(false);
        canContinue();
        getCompSpet();
        canContinue();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * 判断游戏是否结束
     */
    public void canContinue(){
        System.out.println(al.gameState(t3.getChess()));
        if(al.gameState(t3.getChess())==al.WIN ){
            int res=JOptionPane.showConfirmDialog(null, "很遗憾，你输给了电脑，是否再来一局？", "", JOptionPane.YES_NO_OPTION);
                if(res==JOptionPane.YES_OPTION){ 
                  this.setVisible(false);
                   t3.initBroad();
                  // initCheckBroad();
                   new HumanVSComp(name,difficult,firstplace).setVisible(true);
                }else{
                    this.setVisible(false);
                    t3.initBroad();
                    new Choose().setVisible(true);
                }
            
        }else if(al.gameState(t3.getChess())==al.LOSE){
            int res=JOptionPane.showConfirmDialog(null, "恭喜你战胜了电脑，是否再来一局？", "", JOptionPane.YES_NO_OPTION);
                if(res==JOptionPane.YES_OPTION){ 
                  this.setVisible(false);
                   t3.initBroad();
                  // initCheckBroad();
                    new HumanVSComp(name,difficult,firstplace).setVisible(true);
                }else{
                    this.setVisible(false);
                    t3.initBroad();
                
                    new Choose().setVisible(true);
                }
        }else if(al.gameState(t3.getChess())==al.DRAW){
            int res=JOptionPane.showConfirmDialog(null, "你与电脑战成平手，是否再来一局？", "", JOptionPane.YES_NO_OPTION);
                if(res==JOptionPane.YES_OPTION){ 
                  this.setVisible(false);
                   t3.initBroad();
                   //initCheckBroad();
               
                   new HumanVSComp(name,difficult,firstplace).setVisible(true);
                }else{
                    this.setVisible(false);
                    t3.initBroad();
                    new Choose().setVisible(true);
                }
        }
    }
    
    /**
     * 电脑回合
     */
    public void getCompSpet(){
        int pos = t3.comPlace(difficult);
         switch(pos){
                case 0:
                    
                    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                    jButton1.setEnabled(false);
                    break;
                case 1:
                    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                    jButton2.setEnabled(false);
                    break;
                case 2:
                    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                    jButton3.setEnabled(false);
                    break;
                case 3:
                    jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                    jButton4.setEnabled(false);
                    break;
                case 4:
                    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                    jButton5.setEnabled(false);
                    break;   
                case 5:
                    jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                    jButton6.setEnabled(false);
                    break;
                case 6:
                    jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                    jButton7.setEnabled(false);
                    break;
                case 7:
                    jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                    jButton8.setEnabled(false);
                    break;
                case 8:
                    jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                    jButton9.setEnabled(false);
                    break;       
                
            }
    }
    
    
    public void initCheckBroad(){
        jButton1.setIcon(null);
        jButton2.setIcon(null);
        jButton3.setIcon(null);
        jButton4.setIcon(null);
        jButton5.setIcon(null);
        jButton6.setIcon(null);
        jButton7.setIcon(null);
        jButton8.setIcon(null);
        jButton9.setIcon(null);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
    }
        
    /**
     * @param args the command line arguments
     */
 //   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   /*     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HumanVSComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HumanVSComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HumanVSComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HumanVSComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
*/
        /* Create and display the form */
    /*    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HumanVSComp().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
